[versions]

kotlin = "1.9.22"
ktlint-gradle = "12.1.0"
junit = "5.10.2"

[libraries]

junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
ktcompile-testing = { module = "com.github.tschuchortdev:kotlin-compile-testing", version = "1.5.0" }
commons-compress = { module = "org.apache.commons:commons-compress", version = "1.26.1" }

[plugins]

kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-gradle" }
